#!/bin/sh


DEBUG=${DEBUG:-0}


usage_ovpnflexinit ()  {

echo "usage: todo"


}


ovpnflexinit () {


	[ $DEBUG -ge 2 ] && echo "DEBUG2: Entering function \"ovpnflexinit\""

	BASEDIR=${INITDEVBASEDIR:-"/"}
	# Standard BASEDIR may be overriden for development purposes
	[ $DEBUG -ge 6 ] && echo "DEBUG6: Basedir is \"$BASEDIR\""

	BINPATH="usr/local/sbin"
	CONFPATH="etc/ovpnflex"

	# check env
	TUNNAME=${1:-"tun0"}
	[ $DEBUG -ge 6 ] && echo "DEBUG6: Tunname is \"$TUNNAME\""

	## do we have root privileges?
	[ "$USER" = "root" ] || { echo "ERROR: $CALLNAME needs root privileges. Aborting!"; exit 1; }

	# link scripts

	[ $DEBUG -ge 5 ] && echo "DEBUG5: Creating links in Bindir. "
	[ -L "$BASEDIR$BINPATH/ovpnflexctl" ] || ln -s "$BASEDIR$BINPATH/$CALLNAME" "$BASEDIR$BINPATH/ovpnflexctl" 

	# make tunnel  structure

	[ $DEBUG -ge 5 ] && echo "DEBUG5: Creating structure in confdir under \"$BASEDIR$CONFPATH/$TUNNAME\". "

	[ -d "$BASEDIR$CONFPATH/$TUNNAME/plugins/bin" ] || mkdir -p "$BASEDIR$CONFPATH/$TUNNAME/plugins/bin"
	[ -d "$BASEDIR$CONFPATH/$TUNNAME/plugins/etc" ] || mkdir -p "$BASEDIR$CONFPATH/$TUNNAME/plugins/etc"
	[ -d "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/up" ] || mkdir -p "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/up"
	[ -d "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/tls-verify" ] || mkdir -p "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/tls-verify"
	[ -d "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/ipchange" ] || mkdir -p "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/ipchange"
	[ -d "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/client-connect" ] || mkdir -p "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/client-connect"
	[ -d "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/route-up" ] || mkdir -p "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/route-up"
	[ -d "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/route-pre-down" ] || mkdir -p "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/route-pre-down"
	[ -d "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/client-disconnect" ] || mkdir -p "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/client-disconnect"
	[ -d "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/down" ] || mkdir -p "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/down"
	[ -d "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/learn-address" ] || mkdir -p "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/learn-address"
	[ -d "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/auth-user-pass-verify" ] || mkdir -p "$BASEDIR$CONFPATH/$TUNNAME/plugins/script_type/auth-user-pass-verify"

	# default config
	if [ ! -f $BASEDIR$CONFPATH/$TUNNAME/ovpnflex.conf ] ;
	then
		cat >$BASEDIR$CONFPATH/$TUNNAME/ovpnflex.conf <<EOCONF
# This is a default config. All possible parameters 
# are listed below and are shown with their default values.
# To use different values uncomment the line and edit the
# value accordingly.

# which user to use in which stage of privileg escalation
#STAGE0USER="nobody"
#STAGE1USER="openvpn"

# Which name to use for tagging in the logs
#LOGTAG="ovpnflexscript"

#use LOGTAG instead of device name for upmost config directory (actually creates a link)
#MAPDEV2LOGTAG=0
EOCONF

	fi

	. $BASEDIR$CONFPATH/$TUNNAME/ovpnflex.conf

	# set file mode and ownership
	STAGE1USER=${STAGE1USER:-"openvpn"}

	[ $DEBUG -ge 5 ] && echo "DEBUG5: Setting file mode and ownership under \"$BASEDIR$CONFPATH/$TUNNAME\" to root:$STAGE1USER. "

	# structure must be world readable, because it must be read in stage 0 (probably "nobody")
	chown -R root:root "$BASEDIR$CONFPATH/$TUNNAME"
	chmod -R u=rw,g=r,o=r $BASEDIR$CONFPATH/$TUNNAME 
	find $BASEDIR$CONFPATH/$TUNNAME -type d -exec chmod u=rwx,g=rx,o=rx '{}' ';'


	[ $DEBUG -ge 2 ] && echo "DEBUG2: Leaving function \"ovpnflexinit\""

}




CALLNAME="`basename "$0"`"
[ $DEBUG -ge 3 ] && echo "DEBUG3: Callname is \"$CALLNAME\""


case "$CALLNAME" in
	"ovpnflexctl")
		echo "todo: openflexctl"
		;;
	"ovpnflexinit")
		ovpnflexinit "$1"
		;;
	*)	
		echo "Error: You cannot link ovpnflexinit as \"$CALLNAME\". Aborting."
		usage
		;;
esac


